#include<iostream>
using namespace std;
main(){
cout<<"#####    ####   ####   #   #    #####  #####  #     #     #  #     # ######   "<<endl;
cout<<"#    #  #    # #    #  #  #     #      #      #     #     #  ##    # #        "<<endl; 
cout<<"#    #  #    # #    #  # #      #      #      #     #     #  # #   # #        "<<endl;
cout<<"#####   #    # #    #  ##       ####   ####   #     #     #  #  #  # #        "<<endl;
cout<<"#    #  #    # #    #  #  #         #  #      #     #     #  #   # # #  ###   "<<endl;
cout<<"#    #  #    # #    #  #   #        #  #      #     #     #  #    ## #    #   "<<endl;
cout<<"#####    ####   ####   #    #   #####  #####  ##### ##### #  #     # ######   "<<endl;
cout<<endl <<endl;
cout<<"#      # ##### #    # ##### ###### ##### #     # ##### #     # #######    ###### #      # ###### ####### ##### #      #  "<<endl;
cout<<"# #  # # #   # ##   # #   # #      #     # # # # #     ##    #    #       #       #    #  #         #    #     # #  # #  "<<endl;
cout<<"#  #   # ##### # #  # ##### #      ##### #  #  # ####  #  #  #    #       #         ###   #         #    ####  #   #  #  "<<endl; 
cout<<"#      # #   # #  # # #   # #  ### #     #     # #     #   # #    #       ######     #    ######    #    #     #      #  "<<endl; 
cout<<"#      # #   # #   ## #   # #    # #     #     # #     #    ##    #            #     #         #    #    #     #      #  "<<endl;
cout<<"#      # #   # #    # #   # ###### ##### #     # ##### #     #    #       ######     #    ######    #    ##### #      #  "<<endl;
cout<<endl <<endl;
cout<<"Press 1 for New member Registration :" <<endl;
cout<<"Press 2 for Search your favourite books :" <<endl;
cout<<"Press 3 for Search most selling books :" <<endl;
cout<<"Press 4 for if you want full of details in any book :" <<endl;
cout<<"Press 5 for Your data registered if buy the books :" <<endl;
cout<<"Press 6 for Your data registered if borrow the books :" <<endl;
cout<<"Press 7 for Give you conditions if you borrow the books :" <<endl;
cout<<"Press the required key to continue...." <<endl;
cout<<"3" <<endl;
cout<<endl <<endl;
cout<<"Are you student (Yes/No):" <<endl;
string student;
cin>>student;
cout<<"Required book: "<<endl;
string book;
cin>>book;
cout<<"Your bill is: " <<endl;
cout<<"1,156"; 
}
 
